# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
    mod_version=0.1.0
    maven_group=com.example.examplemod
    archives_base_name=examplemod
    mod_id=examplemod
    mod_name=Example Mod
    mod_url=
    mod_author=Example Author
    mod_license=LGPLv3.0